"use client";
import {useEffect,useState} from 'react';
import {MapPin,Search} from 'lucide-react';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
export type Place = { id:string; name:string; country:string; countryCode:string; state:string; latitude:number; longitude:number };
type PickerProps={kind:'country'|'state'|'district'; label:string; country?:Place|null; state?:Place|null; value:Place|null; onChange:(value:Place|null)=>void; disabled?:boolean};
function PlaceSearch({kind,label,country,state,value,onChange,disabled}:PickerProps){
 const [query,setQuery]=useState(''),[results,setResults]=useState<Place[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();setResults([]);setError('');setLoading(false);if(disabled||query.trim().length<2||query===value?.name)return;
 setLoading(true);const timer=setTimeout(async()=>{try{const params=new URLSearchParams({q:query.trim(),kind});if(country)params.set('country',country.countryCode);if(state)params.set('state',state.name);const r=await fetch('/api/places?'+params,{signal:controller.signal});const data=await r.json() as {results:Place[];error?:string};if(!r.ok)throw new Error(data.error||'Search unavailable');if(!controller.signal.aborted)setResults(data.results);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Search unavailable');}finally{if(!controller.signal.aborted)setLoading(false)}},400);return()=>{clearTimeout(timer);controller.abort()}},[query,kind,country,state,disabled,value?.name]);
 return <div className="place-field"><label htmlFor={'birth-'+kind}>{label}</label><Combobox items={results} value={value} inputValue={query} onInputValueChange={(text,details)=>{setQuery(text);if(details.reason==='input-change')onChange(null)}} onValueChange={place=>{onChange(place);setQuery(place?.name||'')}} itemToStringLabel={(item:Place)=>item.name} isItemEqualToValue={(a:Place,b:Place)=>a.id===b.id} filter={null} disabled={disabled}><ComboboxInput id={'birth-'+kind} placeholder={disabled?`Select ${kind==='state'?'country':'state'} first`:`Search ${label.toLowerCase()}…`} className="place-input" aria-describedby={'birth-'+kind+'-status'}/><ComboboxContent className="place-results"><ComboboxEmpty>{loading?'Searching…':error|| (query.trim().length<2?'Type at least 2 letters.':'No matches. Try another spelling.')}</ComboboxEmpty><ComboboxList>{(item:Place)=><ComboboxItem key={item.id} value={item} className="place-option"><MapPin size={15}/><div><b>{item.name}</b><small>{[kind==='district'?item.state:'',kind!=='country'?item.country:''].filter(Boolean).join(', ')}</small></div></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><span className="place-status" id={'birth-'+kind+'-status'} role="status">{loading?'Searching…':error}</span></div>
}
export function BirthLocation({onChange}:{onChange:(place:Place|null)=>void}){const [country,setCountry]=useState<Place|null>(null),[state,setState]=useState<Place|null>(null),[district,setDistrict]=useState<Place|null>(null);return <fieldset className="birth-location"><legend><Search size={15}/> Birthplace</legend><div className="location-search-grid"><PlaceSearch kind="country" label="Country" value={country} onChange={p=>{setCountry(p);setState(null);setDistrict(null);onChange(null)}}/><PlaceSearch key={country?.id||'country-empty'} kind="state" label="State / region" country={country} disabled={!country} value={state} onChange={p=>{setState(p);setDistrict(null);onChange(null)}}/><PlaceSearch key={(country?.id||'')+(state?.id||'state-empty')} kind="district" label="District" country={country} state={state} disabled={!state} value={district} onChange={p=>{setDistrict(p);onChange(p)}}/></div>{district?<p className="selected-birthplace"><MapPin size={15}/>{district.name}, {state?.name}, {country?.name}</p>:<p className="location-help">Search and select your country, then your state and district.</p>}<small className="location-credit">Place search by Photon · <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a></small></fieldset>}
