/** Plain-language demo guidance; not calculated from birth details. */
export function getDemoReply(question: string): string {
 const q=question.toLowerCase();
 if (/marri|love|relationship|partner|crush/.test(q)) return 'For your relationships\nYou do not need to solve everything in one conversation. Start by saying what you need, and give the other person room to share too.\n\nOne small step\nChoose a calm time and say, “I would like us to spend more time together.” Be clear rather than expecting them to guess.\n\nAre you asking about someone you are with, or someone you hope to meet?';
 if (/career|job|work|business|promotion|interview/.test(q)) return 'For your work life\nFocus on the next step you can control. You may get more clarity from trying one small change than from waiting for the perfect moment.\n\nOne small step\nUpdate one part of your CV, practise one interview answer, or ask someone for feedback on your work.\n\nAre you looking for a new job, growing a business, or hoping to progress where you are?';
 if (/money|saving|finance|invest|debt/.test(q)) return 'For your money worries\nStart with a clear picture of what comes in and what goes out. This sample reading cannot predict money gains or tell you which investment to choose.\n\nOne small step\nWrite down your essential expenses and choose one spending habit to review.\n\nIs your main concern saving, spending, or paying off debt?';
 if (/stress|anxious|worry|overwhelm|sad/.test(q)) return 'When things feel heavy\nYou do not have to work everything out today. Choose one concern you can act on and leave the rest for a calmer moment.\n\nOne small step\nTake a short break, then write down the one thing you need help with. Talking to someone you trust can help too.\n\nWhat has been weighing on you most?';
 if (/growth|purpose|future|today|week|focus/.test(q)) return 'A simple place to start\nGive your attention to what matters most to you right now. You do not need to change your whole life at once.\n\nOne small step\nChoose one small goal for this week and set aside ten minutes today to begin.\n\nWould you like to focus on relationships, work, or how you feel?';
 return 'Let’s make this simpler\nI can help you think through a question about relationships, work, money worries, or personal growth. This preview gives sample guidance, not a prediction based on your birth details.\n\nWhat is happening, and what would you most like help understanding?';
}
